### PR TITLE
Add dist files to repo, in order to pull dist files

### PR DESCRIPTION
**Pull request by RomainPrevot**
Hello, 
We are using your library within our application, yet we need our gulp to pull the dist files your removed.

Here's a pull request to put dist files again.

Good job by the way ;)

### CODE REVIEW

**Comment by timcosta** [comment]
Hey @RomainPrevot, thanks for reaching out. The npm installation should include the dist files already, as I am using that in one of my projects. Is that not enough for your use case?

**Comment by RomainPrevot** [comment]
In our case it's not, we just pick all files listed in the "main" section of bower.json.


Do you think it's too heavy for you to maintain the dist files?

**Comment by timcosta** [comment]
Ah, you're using bower and not npm. That was the missing piece. Merging.

**Comment by timcosta** [comment]
Will tag when I get to a computer.

**Comment by RomainPrevot** [comment]
Thanks for the reactivity!

**Comment by timcosta** [comment]
`v3.0.1` has been tagged and released. Hopefully this works for you!

**Comment by RomainPrevot** [comment]
It has pass our CI and automatic regression testing :+1: 
It works like a charm, thank you ;)

**Pull request merged**
